sudo: required

language: go

go:
  - release

services:
  - docker

install:
  - go get github.com/golang/lint/golint
  - go get github.com/xeipuuv/gojsonschema
  - go get github.com/gorilla/mux
  - go get github.com/lib/pq

stages:
  - lint
  - unittest
  - regression

jobs:
  include:
    - stage: lint
      script: $HOME/gopath/bin/golint ./...
    - stage: unittest
      script: go test -v ./api/...
    - stage: regression
      script: ./scripts/deploy.sh